### ISSUE TITLE
GIVE YOUR DISCORD CHANNEL LINK

### ISSUE THREAD

**Issue by Braveheart-judo** [JericoFX/fx-oldmdt#2]
i looked everywhere for jericofx discord channel

**Comment by JericoFX** [comment]
Hi i dont have one, if you need something just add me as a friend JericoFX#3512

**Comment by braveheart12345** [comment]
![image](https://user-images.githubusercontent.com/89262662/204974612-7c132bf4-af39-4236-ab6e-450193b9ced4.png)

**Comment by braveheart12345** [comment]
![image](https://user-images.githubusercontent.com/89262662/204974673-48107492-ef24-4995-afb4-4cfdc50b49fb.png)

**Comment by braveheart12345** [comment]
> Hi i dont have one, if you need something just add me as a friend JericoFX#3512

i want to talk to you about script my discord JUDO#7940

**Comment by yassogmg** [comment]
hi jerikoFX pleas add me in discourd i want to talk with you about your bas  FVM if you can my discourd was ツ么YASSO么#5148 add me
